before_script:
  - "[ $DB == \"mysql\" ] && mysql -e 'create database by_star_test;'"
  - "[ $DB == \"postgres\" ] && psql -c 'create database by_star_test;' -U postgres"

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

script: "DISPLAY=:99.0 bundle exec rspec spec/by_star"

notifications:
  email:
    - radarlistener@gmail.com

branches:
  only:
    - master

rvm:
  - 1.8.7
  - 1.9.3
  - 1.9.2
  - ree
